<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://mpaiement.com/soap"
           xmlns:tns="http://mpaiement.com/soap"
           elementFormDefault="qualified">

    <xs:element name="payerCommandeRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idCommande" type="xs:int"/>
                <xs:element name="montant" type="xs:double"/>
                <xs:element name="numeroCarte" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="payerCommandeResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="idPaiement" type="xs:int"/>
                <xs:element name="idCommande" type="xs:int"/>
                <xs:element name="montant" type="xs:double"/>
                <xs:element name="statut" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
