server.port=9200
spring.application.name=config-server
spring.profiles.active=native
spring.cloud.config.server.native.searchLocations=file:./config-server-repo,file:../config-server-repo,file:../../config-server-repo
eureka.client.service-url.defaultZone=http://localhost:9201/eureka/
eureka.client.registerWithEureka=false
eureka.client.fetchRegistry=false
spring.main.allow-bean-definition-overriding=true
